[dependencies]
"php/php" = "=8.3.4"

[fs]
"/server" = "server"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/server", "-S", "localhost:8080"]

